--create table employee(
--email varchar(30)Not null,
--cantact varchar(10)Not null
--)
--alter table employee alter column email varchar(35)not null
--alter table employee add unique(email)
--alter table employee add unique (email,contact)
--alter table employee add constraint un_emp unique(email)
--alter table employee add constraint unique_emp unique(email,contact)
--alter table employee drop constraint un_emp

